#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Special case handler to rewrite the arguments to `ec2 create-security-group`,
# so as to work around this issue: <https://github.com/aws/aws-cli/issues/7058>

echo "$@"
