#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

# Set up for library-internal usage.
. "${progDir}/init" --lib


#
# Helper functions
#

# Command: Add a subnet to the end of a CIDR's network.
function command_add-subnet {
    case "$#" in
        0|1)
            echo 1>&2 'Missing <cidr> and/or <address> argument.'
            return 1
            ;;
        2)
            : # It's good.
            ;;
        *)
            echo 1>&2 'Too many arguments.'
            return 1
            ;;
    esac

    local cidr="$1"
    local addressAndBits="$2"

    if ! [[ "${addressAndBits}" =~ ^((::[0-9a-f]{1,4})|([0-9]{1,5}))/([0-9]{1,2})$ ]]; then
        echo 1>&2 'Invalid <address> argument.'
        return 1
    fi

    local addressHex="${BASH_REMATCH[2]}"
    local address="${BASH_REMATCH[3]}"
    local bits="${BASH_REMATCH[4]}"

    if [[ ${addressHex} != '' ]]; then
        [[ "${addressHex}" =~ ^::(.*)$ ]]
        addressHex="0x${BASH_REMATCH[1]}"
        address=$(( ${addressHex} )) # Convert hex to dec.
    fi

    if (( ${bits} > 16 )); then
        echo 1>&2 "Too many bits: ${bits}"
        return 1
    elif (( ${address} >= (1 << ${bits}) )); then
        echo 1>&2 "Address does not fit: ${address} in ${bits} bit(s)"
        return 1
    fi

    cidr="$(json-from-any "${cidr}")" \
    || return "$?"

    local netmaskBits="$(jval cidr:json="${cidr}" '$cidr.netmaskBits')"
    local origAddress="$(jval cidr:json="${cidr}" '$cidr.address')"
    local hextetCount="$(jval address:json="${origAddress}" '$address | length')"

    local finalNetmaskBits="$(( ${netmaskBits} + ${bits} ))"
    local newBits=$(( ${address} << (16 - ${bits}) ))
    local partialShift="$(( ${netmaskBits} % 16 ))"

    if (( ${partialShift} != 0 )); then
        local overflow=$(( ${newBits} & ((1 << ${partialShift}) - 1) ))
        local hextet1=$(( ${newBits} >> ${partialShift} ))
        local hextet2=$(( ${overflow} << (16 - ${partialShift}) ))
        newBits=("${hextet1}" "${hextet2}")
        (( netmaskBits -= "${partialShift}" ))
    else
        newBits=("${newBits}")
    fi

    while (( ${netmaskBits} >= 16 )); do
        newBits=(0 "${newBits[@]}")
        (( netmaskBits -= 16 ))
    done

    while (( ${#newBits[@]} < ${hextetCount} )); do
        newBits+=(0)
    done

    newBits="$(lib json-array "${newBits[@]}")"

    newBits="$(jval \
        address:json="${origAddress}" \
        newBits:json="${newBits}" \
        '[$address, $newBits] | transpose | map(.[0] + .[1])'
    )"

    jval \
        cidr:json="${cidr}" \
        address:json="${newBits}" \
        netmaskBits:json="${finalNetmaskBits}" \
        '{
            type: $cidr.type,
            address: $address,
            netmaskBits: $netmaskBits
        }'
}

# Command: Print a CIDR.
function command_print {
    case "$#" in
        0)
            echo 1>&2 'Missing <cidr> argument.'
            return 1
            ;;
        1)
            : # It's good.
            ;;
        *)
            echo 1>&2 'Too many arguments.'
            return 1
            ;;
    esac

    local cidr="$1"

    json-from-any "${cidr}"
}

# Command: Gets the total number of bits in the address.
function command_total-bits {
    case "$#" in
        0)
            echo 1>&2 'Missing <cidr> argument.'
            return 1
            ;;
        1)
            : # It's good.
            ;;
        *)
            echo 1>&2 'Too many arguments.'
            return 1
            ;;
    esac

    local cidr="$1"

    cidr="$(json-from-any "${cidr}")" \
    || return "$?"

    jval cidr:json="${cidr}" '($cidr.address | length) * 16'
}

# Command: Widen the network by a number of bits.
function command_widen {
    case "$#" in
        0|1)
            echo 1>&2 'Missing <cidr> and/or <bits> argument.'
            return 1
            ;;
        2)
            : # It's good.
            ;;
        *)
            echo 1>&2 'Too many arguments.'
            return 1
            ;;
    esac

    local cidr="$1"
    local bits="$2"

    cidr="$(json-from-any "${cidr}")" \
    || return "$?"

    if ! [[ "${bits}" =~ ^0|([1-9][0-9]{0,2})$ ]]; then
        echo 1>&2 'Invalid <bits> argument.'
        return 1
    fi

    totalBits="$(command_total-bits "${cidr}")"
    netmaskBits="$(jval cidr:json="${cidr}" '$cidr.netmaskBits')"
    (( netmaskBits += ${bits} ))

    if (( ${netmaskBits} > ${totalBits} )); then
        echo 1>&2 "Resulting netmask too long: ${netmaskBits}"
        return 1
    fi

    jval \
        cidr:json="${cidr}" \
        netmaskBits:json="${netmaskBits}" \
        '{
            type: $cidr.type,
            address: $cidr.address,
            netmaskBits: $netmaskBits
        }'
}

# Get or validate a JSON-CIDR from the given value. If a standard-form string,
# converts it. If JSON, validates it.
function json-from-any {
    local value="$1"

    if [[ ${value} =~ ^'{' ]]; then
        json-validate "${value}"
    elif [[ ${value} =~ ^[:./0-9a-f]+$ ]]; then
        lib json-from-cidr "${value}"
    else
        echo 1>&2 "Unparseable CIDR: ${value}"
        return 1
    fi
}

# Validates a JSON-CIDR value. On success, prints the value.
function json-validate {
    local value="$1"

    # This doesn't check every possible problem, but it should be sufficient to
    # catch _unintentional_ misuse.
    local result
    result="$(jval cidr:json="${value}" \
        '
            (($cidr | type) == "object")
        and (($cidr | keys) == ["address", "netmaskBits", "type"])
        and (($cidr.address | type) == "array")
        and (($cidr.netmaskBits | type) == "number")
        and (($cidr.netmaskBits >= 0) and ($cidr.netmaskBits <= 128))
        and (($cidr.type == "v4") or ($cidr.type == "v6"))
        |
        if . then $cidr else null end
        '
    )" \
    || return "$?"

    if [[ ${result} == 'null' ]]; then
        echo 1>&2 "Malformed JSON-CIDR: ${value}"
        return 1
    fi

    echo "${result}"
}


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Command.
command=

# Output style.
outputStyle=string

while (( $# > 0 )); do
    case "$1" in
        --compact-json)
            outputStyle=compact-json
            ;;
        --json)
            outputStyle=json
            ;;
        -h|--help)
            showHelp=1
            break
            ;;
        --)
            # Explicit end of options
            shift
            break
            ;;
        -?*)
            echo 1>&2 "Unknown option: $1"
            argError=1
            break
            ;;
        *)
            # Non-option argument
            break
            ;;
    esac

    shift
done

if [[ $# > 0 ]]; then
    command="$1"
    shift
else
    echo 1>&2 'Missing command argument.'
    argError=1
fi

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...] <command> <arg> ..."
    echo ''
    echo 'Performs a calculation of some sort on a CIDR address/mask. Input CIDR'
    echo 'values can be either standard-form strings or parsed JSON values (such'
    echo 'as are produced by the `--json` option of this tool).'
    echo
    echo '--compact-json'
    echo '  Produces compact JSON output.'
    echo '--json'
    echo '  Produces JSON output (a parsed CIDR instead of a standard-form string).'
    echo ''
    echo 'Commands:'
    echo ''
    echo 'add-subnet <cidr> <address>/<bits>'
    echo '  Appends the given number of bits to the end of the CIDR address, with'
    echo '  the given address value. The address must be either a decimal integer'
    echo '  or `::` followed by a hexadecimal integer; and it must fit in the'
    echo '  specified number of bits.'
    echo 'print <cidr>'
    echo '  Prints a CIDR value.'
    echo 'total-bits <cidr>'
    echo '  Gets the total number of bits in the address (not just the netmask).'
    echo 'widen <cidr> <bits>'
    echo '  Widen the address in a CIDR by adding the indicated number of low-order'
    echo '  zero bits.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Displays this message.'
    exit "${argError}"
fi


#
# Main script
#

commandFunc="command_${command}"
if ! declare -F "${commandFunc}" >/dev/null; then
    echo 1>&2 "No such command: ${command}"
    exit 1
fi

result="$("${commandFunc}" "$@")" \
|| exit "$?"

if [[ ${result} =~ ^'{' ]]; then
    # A JSON result is interpreted as a CIDR, in which case the output style
    # matters.
    case "${outputStyle}" in
        compact-json)
            jval --compact result:json="${result}" '$result'
            ;;
        json)
            jval result:json="${result}" '$result'
            ;;
        string)
            lib cidr-from-json "${result}"
            ;;
    esac
else
    # Not a CIDR. Just print the result.
    echo "${result}"
fi
