#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

if [[ ${libDir} != '' ]]; then
    echo 1>&2 'Warning: Not reinitializing library!'
    return 1
fi

if [[ "$1" == '--lib' ]]; then
    libDir="${progDir}"
else
    libDir="${progDir}/lib"
fi

# Calls `json-val`. This script is used enough to warrant having it be easier to
# say than `lib json-val ...`.
function jval {
    lib json-val "$@"
}

# Calls through to an arbitrary library script.
function lib {
    if (( $# == 0 )); then
        echo 1>&2 'Missing library script name.'
        return 1
    fi

    local name="$1"
    shift

    if ! [[ ${name} =~ ^[-a-z]+$ ]]; then
        echo 1>&2 'Weird script name:' "${name}"
        return 1
    elif [[ -x "${libDir}/${name}" ]]; then
        # It's in the internal helper library.
        "${libDir}/${name}" "$@"
    elif [[ -x "${progDir}/${name}" ]]; then
        # It's a "sibling" exposed script.
        "${progDir}/${name}" "$@"
    fi
}

# Calls the prerequisite checker if it doesn't seem to have yet been run in this
# session.
if [[ ${MILKY_CLOUD_PREREQUISITES_DONE} != 1 ]]; then
    if lib check-prerequisites; then
        export MILKY_CLOUD_PREREQUISITES_DONE=1
    else
        echo 1>&2 'Failed one or more prerequisite checks!'
        exit 1
    fi
fi
