#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

# Set up for library-internal usage.
. "${progDir}/init" --lib


#
# Helper functions
#

# Masks an address with a netmask (that is, logical-ANDs the address with the
# netmask). This canonicalizes an address being used as a network specifier.
function mask-address {
    local netmaskBits="$1"
    shift
    local address=("$@")

    local at="$(( ${netmaskBits} / 16 ))"
    local partialBits="$(( ${netmaskBits} % 16 ))"

    if (( ${partialBits} != 0 )); then
        # Mask off the top part of the word that contains the final bit(s) of
        # the network portion of the address.
        local mask
        (( mask = (1 << (${partialBits} + 1)) - 1 ))
        (( mask = ${mask} << (16 - ${partialBits})  ))
        (( address[${at}] &= ${mask} ))
        (( at++ ))
    fi

    while (( ${at} < ${#address[@]} )); do
        (( address[${at}] = 0 ))
        (( at++ ))
    done

    echo "${address[@]}"
}

# Validates and prints out the words (16-bit elements) of an IPv4 address,
# suitable for subsequent inclusion in a final result.
function v4-words {
    local address="$1"
    local errorMsg="Unparseable IPv4 address: ${address}"
    local result=()

    address=".${address}" # Avoids a special case for the first iteration.

    local num
    while [[ ${address} != '' ]]; do
        # `0*` below strips leading zeros, so that the number doesn't get
        # interpreted as octal.
        if ! [[ ${address} =~ ^\.0*([0-9]+)(.*)$ ]]; then
            echo 1>&2 "${errorMsg}"
            return 1
        fi

        num="${BASH_REMATCH[1]}"
        address="${BASH_REMATCH[2]}"

        if (( ${num} > 255 )); then
            echo 1>&2 "${errorMsg}"
            return 1
        fi

        result+=("${num}")
    done

    if (( ${#result[@]} > 4 )); then
        echo 1>&2 "${errorMsg}"
        return 1
    fi

    while (( ${#result[@]} < 4 )); do
        result+=(0)
    done

    # The array form uses 16-bit words, so combine the four 8-bit octets to
    # to produce the final result.
    result=(
        $(( (${result[0]} << 8) + ${result[1]} ))
        $(( (${result[2]} << 8) + ${result[3]} ))
    )
    echo "${result[@]}"
}

# Validates and prints out the  words (16-bit elements) of an IPv6 address,
# suitable for subsequent inclusion in a final result.
function v6-words {
    local address="$1"
    local errorMsg="Unparseable IPv6 address: ${address}"
    local gotGap=0
    local nums=()

    if ! [[ ${address} =~ ^([:0-9a-f]*)(::([:0-9a-f]*))?$ ]]; then
        echo 1>&2 "${errorMsg}"
        return 1
    fi

    while [[ ${address} != '' ]]; do
        if [[ ${address} =~ ^::(.*)$ ]]; then
            if (( ${gotGap} )); then
                # Double gap.
                echo 1>&2 "${errorMsg}"
                return 1
            fi
            gotGap=1
            nums+=(gap)
            address="${BASH_REMATCH[1]}"
        elif [[ ${address} =~ ^([0-9a-f]{1,4})((:.*)|$) ]]; then
            nums+=("0x${BASH_REMATCH[1]}")
            address="${BASH_REMATCH[2]}"
            if [[ ${address} =~ ^:([^:].*)$ ]]; then
                # Strip `:` separator but not `::` gap.
                address="${BASH_REMATCH[1]}"
            fi
        else
            echo 1>&2 "${errorMsg}"
            return 1
        fi
    done

    local zeroCount=0
    if (( ${gotGap} )); then
        if (( ${#nums[@]} > 8 )); then
            echo 1>&2 "${errorMsg}"
            return 1
        fi
        zeroCount=$(( 9 - ${#nums[@]} ))
    else
        if (( ${#nums[@]} != 8 )); then
            echo 1>&2 "${errorMsg}"
            return 1
        fi
    fi

    local result=()
    local n
    for n in "${nums[@]}"; do
        if [[ ${n} == 'gap' ]]; then
            while (( ${zeroCount} > 0 )); do
                result+=(0)
                (( zeroCount-- ))
            done
        else
            # The math expression converts from hex to decimal.
            result+=("$(( ${n} ))")
        fi
    done

    echo "${result[@]}"
}


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# CIDR value.
value=''

while (( $# > 0 )); do
    case "$1" in
        -h|--help)
            showHelp=1
            break
            ;;
        --)
            # Explicit end of options
            shift
            break
            ;;
        -?*)
            echo 1>&2 "Unknown option: $1"
            argError=1
            break
            ;;
        *)
            # Non-option argument
            break
            ;;
    esac

    shift
done

if [[ $# > 0 ]]; then
    value="$1"
else
    echo 1>&2 'Missing CIDR argument.'
    argError=1
fi

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} <cidr>"
    echo ''
    echo 'Converts a CIDR value (either for IPv4 or IPv6) into a JSON object'
    echo 'which can then be used for further and more convenient calculation.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Displays this message.'
    exit "${argError}"
fi


#
# Main script
#

# Note: The repetition limits are generous enough to cover everything valid.
if ! [[ ${value} =~ ^([.:0-9a-f]{1,100})/([1-9][0-9]{0,5})$ ]]; then
    echo 1>&2 "Unparseable CIDR: ${value}"
    exit 1
fi

address="${BASH_REMATCH[1]}"
netmaskBits="${BASH_REMATCH[2]}"
totalBits=
type=

if [[ ${address} =~ : ]]; then
    # It's apparently IPv6.
    type=v6
    totalBits=128
    address=($(v6-words "${address}")) \
    || exit "$?"
elif [[ ${address} =~ \. ]]; then
    # It's apparently IPv4.
    type=v4
    totalBits=32
    address=($(v4-words "${address}")) \
    || exit "$?"
else
    echo 1>&2 "Unparseable CIDR: ${value}"
    exit 1
fi

address=($(mask-address "${netmaskBits}" "${address[@]}"))

jval \
    address:json="$(lib json-array "${address[@]}")" \
    netmaskBits:json="${netmaskBits}" \
    type="${type}" \
    '{
        address: $address,
        netmaskBits: $netmaskBits,
        type: $type
    }'
