#!/bin/bash
#
# Copyright 2022-2023 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# Prerequisite checks for this sublibrary.
#

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"

jqVersion="$(jq 2>/dev/null --version)" \
|| {
    error-msg 'Missing `jq` binary.'
    return 1
}

if ! which aws >/dev/null 2>&1; then
    error-msg 'Missing `aws` binary.'
    return 1
fi
