#!/bin/bash
#
# Copyright 2022-2023 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name}

    Simple wrapper around the AWS command `sts get-caller-identity`, which
    is valid for any valid AWS credentials, and will print out details about
    the identity which owns those credentials.
'

process-args "$@" || usage --short


#
# Main script
#

lib aws-json sts get-caller-identity --global
