#!/bin/bash
#
# Copyright 2022-2025 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Parameters for occasional update.
#

# Path under which Amazon publishes its "latest AMI" pointers.
amiParamPath='/aws/service/ami-amazon-linux-latest'

# Map from OS name (for the `--os` option) to the corresponding parametric name
# under `amiParamPath` for the pointer to the AMI to use.
amiParamNames='{
    "amazon-2023": "al2023-ami-kernel-default-<arch>"
}'


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...]

    Finds an AMI to use when launching an instance. On success, prints a JSON
    object of the salient info.

    --instance-type=<type>
      What type of instance is to be launched. Must be specified.
    --loc=<availability-zone>
      Where the AMI is to be launched. Must be specified.
    --os=<name>
      Which OS to install.
      `amazon-2023` -- Amazon Linux 2023. This is the default, and (as of this
        writing) the only choice.
'

# Availability zone.
opt-value --required --var=zone --call=parse-zone loc

# Instance type.
opt-value --required --var=instanceType \
    --filter='/^[a-z0-9]+\.[a-z0-9]+$/' instance-type

# Which OS.
opt-value --var=osName --default='amazon-2023' \
    --enum[]='amazon-2023' \
    os

process-args "$@" || exit "$?"


#
# Main script
#

# Grab the AMI parameter name (defined at the top of this file).
amiParamName="$(
    jget --output=raw "${amiParamNames}" os="${osName}" '.[$os] // ""'
)"

if [[ ${amiParamName} == '' ]]; then
    # Shouldn't happen; should have been caught by the argument check.
    error-msg "Unknown OS: ${osName}"
    exit 1
fi

# Check to see if the indicated instance type is available in the availability
# zone.

filterSpec="$(lib filter-spec \
    location="${zone}" \
    instance-type="${instanceType}"
)"

foundInstanceType="$(
ec2-json describe-instance-type-offerings \
    --loc="${zone}" \
    filterSpec:json="${filterSpec}" \
    '$filterSpec + { LocationType: "availability-zone" }' \
    :: '.InstanceTypeOfferings | length'
)" \
|| exit "$?"

if (( !foundInstanceType )); then
    error-msg "No such instance type: ${instanceType} in ${zone}"
    exit 1
fi

# `describe-instance-types` to extract the supported architecture, ignoring
# `i386` which we don't care about (`x86_64` is the modern choice).

architecture="$(
ec2-json describe-instance-types \
    --loc="${zone}" \
    instanceType="${instanceType}" \
    '{ InstanceTypes: [$instanceType] }' \
    :: --output=raw '
        .InstanceTypes[0].ProcessorInfo.SupportedArchitectures
        | map(select(. != "i386"))
        | .[0] // "error"
    '
)" \
|| exit "$?"

if [[ ${architecture} == 'error' ]]; then
    error-msg "Unsupported instance type: ${instanceType} in ${zone}"
    exit 1
fi

# Find the AMI ID.
amiParamName="${amiParamName//<arch>/${architecture}}"
imageId="$(
lib aws-json ssm get-parameter \
    --loc="${zone}" \
    name="${amiParamPath}/${amiParamName}" \
    '{ Name: $name }' \
    :: --output=raw '.Parameter.Value'
)" \
|| exit "$?"

result="$(ec2-json describe-images \
    --loc="${zone}" \
    imageId="${imageId}" \
    '{ ImageIds: [$imageId] }' \
    :: '
    if .Images == []
    then
        null
    else
        .Images[0]
        |
        {
            Description: .Description,
            ImageId:     .ImageId,
            Name:        .Name
        }
    end'
)" \
|| exit "$?"

if [[ ${result} == 'null' ]]; then
    error-msg 'Eek! Did not find a matching AMI!'
    error-msg '(Did Amazon just do something weird?)'
    exit 1
fi

jget "${result}"
