#!/bin/bash
#
# Copyright 2022-2023 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...]

    Lists all accessible availability zones in a given region.

    --loc=<region-or-zone>
      What region to look in. Must be specified. If specified as an availability
      zone, only the region portion matters.
    --output=<style> :: `compact` `json` `lines`
      Output style, as with `jval`. Defaults to `lines`, which indicates _raw_
      lines (no JSON decoration).
'

# Region, passed as either region per se or availability zone.
opt-value --required --var=region --filter=region-from-location loc

# Output style.
opt-value --var=outputStyle --default=lines --enum[]='compact json lines' output

process-args "$@" || exit "$?"


#
# Main script
#

if [[ ${outputStyle} == 'lines' ]]; then
    outputStyle='raw'
fi

cmd=(ec2-json describe-availability-zones
    --loc="${region}"
    :: --output="${outputStyle}" '.AvailabilityZones | map(.ZoneName) | sort')

if [[ "${outputStyle}" == 'raw' ]]; then
    cmd+=('| .[]')
fi

"${cmd[@]}"
