#!/bin/bash
#
# Copyright 2022-2023 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} [<suffix>]

    Prints a standardized timestamp representing "now" with an optional suffix.
    This can be used to label things that have nothing more suitable.

    ${name} [--help | -h]

    Displays this message.
'

# Want help?
opt-action --call='{ usage; exit }' help/h

# Suffix text.
positional-arg --var=suffix --filter='/^[-_:./a-zA-Z0-9]+$/' suffix

process-args "$@" || usage --short


#
# Main script
#

if [[ ${suffix} != '' ]]; then
    suffix="-${suffix}"
fi

echo "$(date -u '+%Y-%m-%d-%H%M%S')${suffix}"
