#!/bin/bash

# Replace with a valid VPC ID.
vpcId='vpc-xxxxxxxx'
vpcId='vpc-aa6acfcf'

groupId="$(
aws ec2 create-security-group --output json --region us-west-2 \
    --description test --group-name test --vpc-id "${vpcId}" \
| jq --raw-output '.GroupId'
)"

echo "Group ID: ${groupId}"

jsonArg="$(jq -n --arg groupId "${groupId}" '
{
  GroupId: $groupId,
  IpPermissions: [
    {
      FromPort: -1,
      ToPort: -1,
      IpProtocol: "-1"
    }
  ],
  TagSpecifications: [
    {
      ResourceType: "security-group-rule",
      Tags: [
        {
          Key: "Name",
          Value: "hello-there"
        }
      ]
    }
  ]
}
')"

#aws ec2 authorize-security-group-egress --output json --region us-west-2 \
#    --cli-input-json "${jsonArg}"

aws ec2 authorize-security-group-egress --debug \
    --output json --region us-west-2 \
    --group-id "${groupId}" \
    --ip-permissions 'FromPort=-1,ToPort=-1,IpProtocol=-1' \
    --tag-specifications \
    'ResourceType=security-group-rule,Tags=[{Key=Name,Value=hello-there}]' 2>debug-log.txt

aws ec2 describe-security-group-rules --output json --region us-west-2 \
    --filters Name=group-id,Values="${groupId}" \
| jq '.SecurityGroupRules[] | [.SecurityGroupRuleId, .Tags]'
