#!/bin/bash
#
# Copyright 2022-2023 the Milky-cloud Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"
. "$(this-cmd-dir)/control-help.sh"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...] [:: [<out-opt> ...] [<jval-expr> ...]]

    Terminates one or more instances. Options are passed through to `instance info`
    to determine which instance(s) to act on.

    By default, this command prints the result of the `instance info` which
    selected instances. This can be altered via the `--output=<style>` option and
    any post-processing arguments.

    Options:
      --attributes
      --default-loc=<region-or-zone>
      --default-vpc=<id-spec>
      --expired=<choice> :: `exclude` `include` `only`
      --id=<id-spec>
      --multiple
      --not-found-ok
      --output (sort of; applies to final output)
      --protected
'

# Options and arguments passed through to `instance info`.
usual-info-args

process-args "$@" || usage --short


#
# Main script
#

instance-control-ec2 terminate-instances 'Terminating'
