#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} <subcommand> ... [<opt> ...] [--] [<arg> ...]
      Runs a subcommand. <opt>s and <arg>s depend on the specific subcommand.
'

# The subcommand.
positional-arg --var=cmdName subcommand

# The subcommand arguments (including possibly sub-subcommand names).
rest-arg --var=args args

process-args "$@" || exit "$?"


#
# Main script
#

unitsOpt='--units=milky-cloud'

if [[ ${cmdName} == '' ]]; then
    lib helpy print-all-commands "${unitsOpt}" --prefix="$(this-cmd-name) "
    exit 1
fi

lib "${unitsOpt}" --quiet "${cmdName}" "${args[@]}"
exitCode="$?"

if (( exitCode == 127 )); then
    error-msg "Command not found: ${cmdName}"
    error-msg
    lib helpy print-all-commands "${unitsOpt}" --prefix="$(this-cmd-name) "
    exit 1
fi

exit "${exitCode}"
