#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

# Load the helper library.
. "${progDir}/lib/init"


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Location (region or availability zone).
inLocation=''

# Print full object?
printAll=0

while (( $# > 0 )); do
    case "$1" in
        --in=?*)
            inLocation="${1#*=}"
            ;;
        -h|--help)
            showHelp=1
            break
            ;;
        --print-all)
            printAll=1
            ;;
        --)
            # Explicit end of options
            shift
            break
            ;;
        -?*)
            echo 1>&2 "Unknown option: $1"
            argError=1
            break
            ;;
        *)
            # Non-option argument
            break
            ;;
    esac

    shift
done

if (( !argError && ($# < 1) )); then
    echo 1>&2 'Missing argument: name or ID'
    argError=1
else
    nameOrId="$1"
    shift
fi

if (( !argError )); then
    if [[ ${inLocation} == '' ]]; then
        echo 1>&2 'Missing option: --in'
        argError=1
    fi
fi

if (( argError )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...] <name-or-id>"
    echo '  Finds a security group by name or validates the existence of one by'
    echo '  ID. If passed an ID, it can either be the ID of a security group per'
    echo '  se, or it can be an ID of a VPC which is taken to refer to the default'
    echo '  security group for the indicated VPC. On success, prints the security'
    echo '  group ID (by default) or the entire group info object.'
    echo ''
    echo '  --in=<region-or-zone>'
    echo '    Where to look. Must be specified. If specified as an availability'
    echo '    zone, only the region portion matters.'
    echo '  --print-all'
    echo '    Print the full info object, not just the ID.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Displays this message.'
    exit $(( argError < 0 ? 0 : argError ))
fi


#
# Main script
#

inRegion="$(lib region-from-location "${inLocation}")" \
|| exit "$?"

filterSpec=''
if [[ ${nameOrId} =~ ^sg- ]]; then
    # It looks like a security group ID.
    filterSpec="$(lib filter-spec group-id="${nameOrId}")"
elif [[ ${nameOrId} =~ ^vpc- ]]; then
    # It looks like a VPC ID.
    filterSpec="$(lib filter-spec group-name=default vpc-id="${nameOrId}")"
else
    # It's expected to be the name of a security group.
    filterSpec="$(lib filter-spec group-name="${nameOrId}")"
fi

result="$(
ec2-json describe-security-groups \
    --in="${inRegion}" \
    "${filterSpec}" \
    :: \
    '
        .SecurityGroups
        |
        {
            count: (. | length),
            group: .[0],
            all:   map(.GroupId + " " + (.GroupName | tojson))
        }
    '
)" \
|| exit "$?"

count="$(jget "${result}" '.count')"

if (( count == 0 )); then
    echo 1>&2 "No such security group: ${nameOrId}"
    exit 1
elif (( count != 1 )); then
    echo 1>&2 'Ambiguous name or ID matches all of:'
    jget --raw 1>&2 "${result}" '.all[] | "  " + .'
    exit 1
fi

if (( printAll )); then
    jget "${result}" '.group'
else
    jget --raw "${result}" '.group.GroupId'
fi
