#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Location (availability zone).
inLocation='us-west-2a'

# Instance type.
instanceType='t3.nano'

while true; do
    case "$1" in
        -h|--help)
            showHelp=1
            break
            ;;
        --in=?*)
            inLocation="${1#*=}"
            ;;
        --instance-type=?*)
            instanceType="${1#*=}"
            ;;
        --) # End of all options
            shift
            break
            ;;
        -?*)
            echo 1>&2 "Unknown option: $1"
            argError=1
            break
            ;;
        *)  # Default case: No more options, break out of the loop.
            break
    esac

    shift
done

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...]"
    echo '  Launches a standard-configured instance.'
    echo ''
    echo '  --in=<availability-zone>'
    echo '    Where to launch.'
    echo '  --instance-type=<type>'
    echo '    What type of instance to install.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Display this message.'
    exit ${argError}
fi


#
# Main script
#

"${progDir}/aws-preflight" || exit "$?"

# Figure out the correct image ID.
imageId="$(${progDir}/find-image-id \
    --in="${inLocation}" --instance-type="${instanceType}")"

if [[ $? != 0 ]]; then
    exit "$?"
fi

# Stuff goes here!
echo '### Stuff goes here!'
exit 1

aws ec2 run-instances \
    --image-id="${imageId}" \
    --instance-type="${instanceType}"
