#!/bin/bash
#
# Copyright 2022 Dan Bornstein.
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

# Load the helper library.
. "${progDir}/lib/init"


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Location (availability zone).
inLocation='us-west-2a'

# Instance type.
instanceType='t3.nano'

# Name for the SSH keypair that allows for login access.
keyName=''

# Name for the resulting instance.
name=''

# Security group to use (name or id), if any.
securityGroup=''

while (( $# > 0 )); do
    case "$1" in
        --in=?*)
            inLocation="${1#*=}"
            ;;
        --instance-type=?*)
            instanceType="${1#*=}"
            ;;
        --key-name=?*)
            keyName="${1#*=}"
            ;;
        --name=?*)
            name="${1#*=}"
            ;;
        --security-group=?*)
            securityGroup="${1#*=}"
            ;;
        -h|--help)
            showHelp=1
            break
            ;;
        --)
            # Explicit end of options
            shift
            break
            ;;
        -?*)
            echo 1>&2 "Unknown option: $1"
            argError=1
            break
            ;;
        *)
            # Non-option argument
            break
            ;;
    esac

    shift
done

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...]"
    echo '  Launches a standard-configured instance. On success, prints a JSON'
    echo '  object with the most-salient values (including notably the'
    echo '  instance ID).'
    echo ''
    echo '  --in=<availability-zone>'
    echo '    Where to launch.'
    echo '  --instance-type=<type>'
    echo '    What type of instance to install.'
    echo '  --key-name=<name>'
    echo '    Name of the keypair to use for SSH access.'
    echo '  --name=<name>'
    echo '    Name (label) for the resulting instance.'
    echo '  --security-group=<name-or-id>'
    echo '    Name or ID of the security group to use for network access control.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Display this message.'
    exit "${argError}"
fi


#
# Main script
#

inRegion="$(lib region-from-zone "${inLocation}")" \
|| exit "$?"

echo 1>&2 "type: ${instanceType}"
echo 1>&2 "in:   ${inRegion} / ${inLocation}"

# Figure out the correct AMI.

amiInfo="$(
${progDir}/find-ami \
    --in="${inLocation}" --instance-type="${instanceType}"
)"

if (( $? != 0 )); then
    exit "$?"
fi

jval 1>&2 --raw "${amiInfo}" \
    '| (
        "Using AMI:",
        "  desc: " + .Description,
        "  name: " + .Name,
        "  id:   " + .ImageId
    )'

# Resolve the security group and subnet IDs, if necessary.

subnetId=''
if [[ ${securityGroup} != '' ]]; then
    securityGroup="$(lib find-security-group --in="${inLocation}" "${securityGroup}")" \
    || exit 1
    vpcId="$(lib find-vpc --in="${inLocation}" "${securityGroup}")" \
    || exit 1
    subnetId="$(lib find-vpc-subnet --in="${inLocation}" --vpc="${vpcId}")" \
    || exit 1
fi

# Make up a name if one wasn't provided.
if [[ ${name} == '' ]]; then
    now="$(date -u '+%Y-%m-%d-%H:%M:%S')"
    name="${now}-via-script"
fi

# Form the main command, and do it!

# Label for the command, which get spit out immediately below.
echo 1>&2 ''
echo 1>&2 'Launch command:'

# Note: If a subnet ID is provided, then it implies the availability zone, in
# which case one doesn't also need to specify the availability zone explicitly.
# However, it's easier just to include it because this script is also meant to
# work when a security group and subnet aren't specified.
#
# Note: Public IP and DNS are de facto (usually?) not set in the output from
# `ec2 run-instances`.
ec2-json run-instances \
    --in="${inRegion}" \
    --print-command-to=/dev/stderr \
    amiInfo:json="${amiInfo}" \
    inLocation="${inLocation}" \
    instanceType="${instanceType}" \
    keyName="${keyName}" \
    securityGroup="${securityGroup}" \
    subnetId="${subnetId}" \
    tagSpec:json="$(lib name-tag-spec instance "${name}")" \
    '
        {
            ImageId:      $amiInfo.ImageId,
            InstanceType: $instanceType,
            MaxCount:     1,
            Placement:    { AvailabilityZone: $inLocation }
        }
        + $tagSpec
        + if $keyName == "" then {} else { KeyName: $keyName } end
        + if $securityGroup == "" then {} else { SecurityGroupIds: [$securityGroup] } end
        + if $subnetId == "" then {} else { SubnetId: $subnetId } end
    ' \
    :: \
    '
        .Instances[0]
        |
        {
            InstanceId: .InstanceId,
            PrivateDnsName: .PrivateDnsName,
            PrivateIpAddress: .PrivateIpAddress
        }
    '
